corner_radius 10
gaps inner 5
gaps outer 5
gaps bottom 0
hide_edge_borders smart
smart_gaps on

for_window [app_id="keylist"] floating enable, border none

output * {
    # hmm latency things. change if screen tearing
    max_render_time off
    allow_tearing yes
    adaptive_sync on
}



default_border pixel 2
default_floating_border pixel 2

# styling
set $bg #282828
set $fg #ebdbb2
set $border #928374
set $active #b4befe
set $inactive #3c3836
set $urgent #cc241d
client.focused          $active $active $fg $active $active
client.focused_inactive $inactive $inactive $fg $inactive $inactive
client.unfocused        $bg $bg $border $bg $bg
client.urgent           $urgent $urgent $fg $urgent $urgent



set $mod Mod4

# focus
bindsym $mod+j focus left
bindsym $mod+l focus right
bindsym $mod+k focus down
bindsym $mod+i focus up
bindsym $mod+Left focus left
bindsym $mod+Right focus right
bindsym $mod+Down focus down
bindsym $mod+Up focus up

bindsym $mod+Shift+j move left
bindsym $mod+Shift+l move right
bindsym $mod+Shift+k move down
bindsym $mod+Shift+i move up
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up

bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5

bindsym $mod+Ctrl+1 workspace 6
bindsym $mod+Ctrl+2 workspace 7
bindsym $mod+Ctrl+3 workspace 8
bindsym $mod+Ctrl+4 workspace 9
bindsym $mod+Ctrl+5 workspace 10

bindsym $mod+Mod1+1 workspace 11
bindsym $mod+Mod1+2 workspace 12
bindsym $mod+Mod1+3 workspace 13
bindsym $mod+Mod1+4 workspace 14
bindsym $mod+Mod1+5 workspace 15

bindsym $mod+Shift+1 shift_workspace 1
bindsym $mod+Shift+2 shift_workspace 2
bindsym $mod+Shift+3 shift_workspace 3
bindsym $mod+Shift+4 shift_workspace 4
bindsym $mod+Shift+5 shift_workspace 5
